# RDS Postgres (spec §8).
#
# Private subnets, no public IP, ingress from the application security group only. A developer
# reaches it with `aws ecs execute-command` into a running task, not through a bastion.
#
# This module creates the INSTANCE and never the SCHEMA. Migrations live in
# services/wallet-api/migrations/ and are applied by the one-shot migrate task (spec §7.7).

terraform {
  required_version = ">= 1.10"
  required_providers {
    aws    = { source = "hashicorp/aws", version = "~> 6.0" }
    random = { source = "hashicorp/random", version = "~> 3.6" }
  }
}

resource "aws_db_subnet_group" "this" {
  name       = var.name
  subnet_ids = var.subnet_ids
}

# Generated, never supplied. A password in tfvars is a password in a pull request.
# It does land in Terraform state, which is why the state bucket is private, versioned and
# encrypted (bootstrap/main.tf) — see spec §17 R6.
resource "random_password" "master" {
  length = 32
  # RDS rejects '/', '@', '"' and ' ' in a master password, and the DSN below would have to
  # percent-encode anything exotic. Alphanumeric sidesteps both problems.
  special = false
}

resource "aws_db_parameter_group" "this" {
  name   = var.name
  family = "postgres17"

  # Log anything slower than a second. Cheap, and it is the first thing anyone asks for.
  parameter {
    name  = "log_min_duration_statement"
    value = "1000"
  }
}

resource "aws_db_instance" "this" {
  identifier     = var.name
  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = var.database_name
  username = var.master_username
  password = random_password.master.result
  port     = 5432

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [var.security_group_id]
  parameter_group_name   = aws_db_parameter_group.this.name
  publicly_accessible    = false
  multi_az               = var.multi_az

  backup_retention_period = var.backup_retention_period
  backup_window           = "02:00-03:00"
  maintenance_window      = "Mon:03:30-Mon:04:30"

  auto_minor_version_upgrade = true
  apply_immediately          = var.apply_immediately

  performance_insights_enabled = false
  monitoring_interval          = 0

  # The two lines that make this a DEV database. Both must flip for staging.
  deletion_protection = var.deletion_protection
  skip_final_snapshot = var.skip_final_snapshot

  # Terraform would otherwise propose a diff on every plan once RDS applies a minor upgrade.
  lifecycle {
    ignore_changes = [engine_version]
  }
}

# ── the DSN ────────────────────────────────────────────────────────────────────────────────
#
# wallet-api consumes DATABASE_URL, not a host/user/password triple, so the composed DSN is
# what goes into SSM. Written here rather than in the root module because only this module
# knows the generated password.

resource "aws_ssm_parameter" "database_url" {
  name        = "${var.ssm_path_prefix}/database-url"
  description = "Postgres DSN for wallet-api. Generated by Terraform."
  type        = "SecureString"
  value       = "postgres://${var.master_username}:${random_password.master.result}@${aws_db_instance.this.address}:${aws_db_instance.this.port}/${var.database_name}"
}
