/**
 * Generates addresses.ts (the committed per-chain address registry) from the
 * git-tracked Hardhat Ignition journals plus address-overrides.json.
 *
 * Run with: pnpm gen:addresses  (CI re-runs it and fails on drift)
 */
import * as fs from 'fs';
import * as path from 'path';

const pkgRoot = path.resolve(__dirname, '..');
const deploymentsDir = path.join(pkgRoot, 'ignition', 'deployments');
const overridesPath = path.join(pkgRoot, 'address-overrides.json');
const outPath = path.join(pkgRoot, 'addresses.ts');

/** Ignition future id → registry field. Optional fields may be absent on production chains. */
const FUTURE_TO_FIELD: Record<string, { field: string; optional: boolean }> = {
  'GianoAccountFactory#GianoSmartWalletFactory': { field: 'factory', optional: false },
  'GianoAccountFactory#GianoSmartWallet': { field: 'implementation', optional: false },
  'Testing#PermissivePaymaster': { field: 'paymaster', optional: true },
  'Testing#PrivateERC20': { field: 'testErc20', optional: true },
};

type Overrides = Record<string, Record<string, string>>;

function isAddress(value: unknown): value is string {
  return typeof value === 'string' && /^0x[0-9a-fA-F]{40}$/.test(value);
}

function main(): void {
  const overrides: Overrides = JSON.parse(fs.readFileSync(overridesPath, 'utf8'));
  delete overrides.$comment;

  const chains: Record<number, Record<string, string>> = {};

  for (const entry of fs.readdirSync(deploymentsDir).sort()) {
    const match = /^chain-(\d+)$/.exec(entry);
    if (!match) continue;
    const chainId = Number(match[1]);
    if (chainId === 31337) continue; // local devnet deployments are never committed

    const deployedPath = path.join(deploymentsDir, entry, 'deployed_addresses.json');
    if (!fs.existsSync(deployedPath)) continue;
    const deployed: Record<string, string> = JSON.parse(fs.readFileSync(deployedPath, 'utf8'));

    const record: Record<string, string> = {};
    for (const [futureId, address] of Object.entries(deployed)) {
      const mapping = FUTURE_TO_FIELD[futureId];
      if (!mapping) continue;
      if (!isAddress(address)) throw new Error(`Invalid address for ${futureId} on chain ${chainId}: ${address}`);
      record[mapping.field] = address;
    }

    for (const [field, meta] of Object.entries(FUTURE_TO_FIELD)) {
      if (!meta.optional && !record[meta.field]) {
        throw new Error(`chain ${chainId}: missing required future ${field}`);
      }
    }

    chains[chainId] = record;
  }

  const defaults = overrides.default ?? {};
  for (const chainId of Object.keys(chains)) {
    const merged = { ...defaults, ...(overrides[chainId] ?? {}) };
    for (const [field, address] of Object.entries(merged)) {
      if (!isAddress(address)) throw new Error(`Invalid override address for chain ${chainId}.${field}: ${address}`);
      chains[Number(chainId)][field] = address;
    }
  }

  const fieldOrder = ['entryPoint', 'factory', 'implementation', 'paymaster', 'testErc20'];

  const chainBlocks = Object.entries(chains)
    .sort(([a], [b]) => Number(a) - Number(b))
    .map(([chainId, record]) => {
      const lines = fieldOrder
        .filter((field) => record[field])
        .map((field) => `    ${field}: '${record[field]}',`)
        .join('\n');
      return `  ${chainId}: {\n${lines}\n  },`;
    })
    .join('\n');

  const output = `// AUTO-GENERATED by scripts/generate-addresses.ts — do not edit by hand.
// Source of truth: ignition/deployments/chain-*/deployed_addresses.json + address-overrides.json.
// Regenerate with: pnpm gen:addresses (CI fails on drift).

/** Canonical ERC-4337 EntryPoint v0.7. */
export const ENTRYPOINT_V07_ADDRESS = '0x0000000071727De22E5E9d8BAf0edAc6f37da032' as const;

export type GianoDeployment = {
  /** ERC-4337 EntryPoint the wallets are bound to. */
  entryPoint: \`0x\${string}\`;
  /** GianoSmartWalletFactory. */
  factory: \`0x\${string}\`;
  /** GianoSmartWallet implementation behind the factory's proxies. */
  implementation: \`0x\${string}\`;
  /** Testing-only permissive paymaster (not deployed on production chains). */
  paymaster?: \`0x\${string}\`;
  /** Testing-only ERC-20 (not deployed on production chains). */
  testErc20?: \`0x\${string}\`;
};

export const gianoAddresses: Record<number, GianoDeployment> = {
${chainBlocks}
};

/** Returns the Giano deployment for a chain, throwing a descriptive error for unknown chains. */
export function getGianoDeployment(chainId: number): GianoDeployment {
  const deployment = gianoAddresses[chainId];
  if (!deployment) {
    const known = Object.keys(gianoAddresses).join(', ');
    throw new Error(\`No Giano deployment registered for chain \${chainId}. Known chains: \${known}\`);
  }
  return deployment;
}
`;

  fs.writeFileSync(outPath, output);
  console.log(`Wrote ${path.relative(process.cwd(), outPath)} (${Object.keys(chains).length} chains)`);
}

main();
