import React from 'react';
import { testContractAbi } from '@appliedblockchain/giano-contracts';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useAccount, useWriteContract } from 'wagmi';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { isConnected } = useAccount();
  const { writeContractAsync, isPending } = useWriteContract();

  const TESTING_CONTRACT_ADDRESS = '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9';

  const sendTx = async () => {
    const result = await writeContractAsync({
      address: TESTING_CONTRACT_ADDRESS,
      abi: testContractAbi,
      functionName: 'setMessage',
      args: ['Hello!'],
    });
    console.log(result);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Giano Demo</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <button disabled={!isConnected || isPending} onClick={sendTx}>
          Send Hello Tx
        </button>
      </main>
    </div>
  );
};

export default Home;
