import { privateErc20Abi } from '@appliedblockchain/giano-contracts';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import 'react';
import type { FormEvent } from 'react';
import { useEffect, useState } from 'react';
import { formatEther, parseEther } from 'viem';
import { useAccount, useReadContract, useWriteContract } from 'wagmi';
import styles from '../styles/Home.module.css';

const CREDENTIAL_MAPPER_ADDRESS = '0x2BF3Ec07f07C52df9DE3Ac40e142d64F95762ECB';
const PRIVATE_ERC20_ADDRESS = '0xA6ED5f9baB12B749CD9Dc2ED73320eadb055D9B9';
const PAYMASTER_ADDRESS = '0x0A8285879FD97FBe15f9402fDED9511Ef3Abf04d';
const Home: NextPage = () => {
  const { address, isConnected } = useAccount();
  const { writeContractAsync, isPending: isWritePending } = useWriteContract();
  const {
    refetch: readContract,
    isPending: isReadPending,
    error,
  } = useReadContract({
    address: PRIVATE_ERC20_ADDRESS,
    abi: privateErc20Abi,
    functionName: 'balanceOf',
    args: [address!],
    query: {
      enabled: !!address,
      retry: false,
      retryOnMount: false,
    },
  });

  const [inputMessage, setInputMessage] = useState('');
  const [contractState, setContractState] = useState<bigint | null>(null);
  useEffect(() => {
    if (error) {
      console.error(error);
    }
  }, [error]);

  const sendTx = async (e: FormEvent & { currentTarget: HTMLFormElement }) => {
    e.preventDefault();
    if (!inputMessage.trim()) return;
    const result = await writeContractAsync({
      address: PRIVATE_ERC20_ADDRESS,
      abi: privateErc20Abi,
      functionName: 'mint',
      args: [parseEther(inputMessage.trim())],
    });
    console.log(result);
  };

  const sendCall = async () => {
    const { data } = await readContract();
    if (data) setContractState(data);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Giano Demo</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <form className={styles.formContainer} onSubmit={sendTx}>
          <input className={styles.input} type="number" placeholder="Enter amount" value={inputMessage} onChange={(e) => setInputMessage(e.target.value)} />
          <button className={styles.sendButton} disabled={!isConnected || isWritePending || !inputMessage.trim()}>
            Mint
          </button>
        </form>
        <button className={styles.readButton} disabled={!isConnected || isReadPending} onClick={sendCall}>
          Read balance
        </button>

        {contractState && (
          <div className={styles.stateCard}>
            <p>
              <strong>Balance:</strong> {formatEther(contractState)}
            </p>
          </div>
        )}
        {error && <p>Error reading balance: {error.message}</p>}
      </main>
    </div>
  );
};

export default Home;
