import { privateErc20Abi } from '@appliedblockchain/giano-contracts'
import type { NextPage } from 'next'
import Head from 'next/head'
import React, { type FormEvent } from 'react'
import { useEffect, useState } from 'react'
import { formatEther, parseEther } from 'viem'
import {
  useAccount,
  useConnect,
  useDisconnect,
  useReadContract,
  useWalletClient,
  useWriteContract,
} from 'wagmi'
import styles from '../styles/Home.module.css'
import { gianoConnector } from '../wagmi'

const PRIVATE_ERC20_ADDRESS = '0xA6ED5f9baB12B749CD9Dc2ED73320eadb055D9B9'

const Home: NextPage = () => {
  const { connect } = useConnect()
  const { disconnect } = useDisconnect()
  const { address, isConnected } = useAccount()
  const { data: walletClient } = useWalletClient()
  const { writeContractAsync, isPending: isWritePending } = useWriteContract()
  const {
    refetch: readContract,
    isPending: isReadPending,
    error,
  } = useReadContract({
    address: PRIVATE_ERC20_ADDRESS,
    abi: privateErc20Abi,
    functionName: 'balanceOf',
    args: [address!],
    query: {
      enabled: !!address,
      retry: false,
      retryOnMount: false,
    },
  })

  const [inputMessage, setInputMessage] = useState('')
  const [contractState, setContractState] = useState<bigint | null>(null)
  const [signatureResult, setSignatureResult] = useState<string>('')
  const [messageToSign, setMessageToSign] = useState('Hello, please sign this message!')

  useEffect(() => {
    if (error) {
      console.error(error)
    }
  }, [error])

  const sendTx = async (e: FormEvent & { currentTarget: HTMLFormElement }) => {
    e.preventDefault()
    if (!inputMessage.trim()) return
    const result = await writeContractAsync({
      address: PRIVATE_ERC20_ADDRESS,
      abi: privateErc20Abi,
      functionName: 'mint',
      args: [parseEther(inputMessage.trim())],
    })
  }

  const sendCall = async () => {
    const { data } = await readContract()
    if (data) setContractState(data)
  }
  
  const signMessage = async () => {
    if (!walletClient || !address) {
      console.error('Wallet not connected')
      return
    }

    try {
      const signature = await walletClient.signMessage({
        message: messageToSign,
      } as any)
      setSignatureResult(signature as string)
      console.log('Message signed successfully:', signature)
    } catch (error) {
      console.error('Message signing failed:', error)
      setSignatureResult('Error: ' + (error as Error).message)
    }
  }

  const signTypedData = async () => {
    if (!walletClient || !address) {
      console.error('Wallet not connected')
      return
    }

    try {
      // Example EIP-712 typed data
      const typedData = {
        domain: {
          name: 'Giano Demo',
          version: '1',
          chainId: 1,
          verifyingContract: '0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC',
        },
        types: {
          Message: [
            { name: 'content', type: 'string' },
            { name: 'timestamp', type: 'uint256' },
          ],
        },
        primaryType: 'Message',
        message: {
          content: 'Hello from Giano!',
          timestamp: Math.floor(Date.now() / 1000),
        },
      }

      const signature = await walletClient.request({
        method: 'eth_signTypedData_v4',
        params: [address, JSON.stringify(typedData)],
      } as any)
      
      setSignatureResult(signature as string)
      console.log('Typed data signed successfully:', signature)
    } catch (error) {
      console.error('Typed data signing failed:', error)
      setSignatureResult('Error: ' + (error as Error).message)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Giano Demo</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        {isConnected
          ? <button onClick={() => disconnect()}>Disconnect</button>
          : <button onClick={() => connect({ connector: gianoConnector })}>Connect</button>
        }
        <form className={styles.formContainer} onSubmit={sendTx}>
          <input className={styles.input} type="number" placeholder="Enter amount" value={inputMessage} onChange={(e) => setInputMessage(e.target.value)} />
          <button className={styles.sendButton} disabled={!isConnected || isWritePending || !inputMessage.trim()}>
            Mint
          </button>
        </form>
        <button className={styles.readButton} disabled={!isConnected || isReadPending} onClick={sendCall}>
          Read balance
        </button>

        {/* Message Signing Section */}
        <div className={styles.formContainer}>
          <input 
            className={styles.input} 
            type="text" 
            placeholder="Message to sign" 
            value={messageToSign} 
            onChange={(e) => setMessageToSign(e.target.value)} 
          />
          <button 
            className={styles.readButton} 
            disabled={!isConnected} 
            onClick={signMessage}
          >
            Sign Message (Personal)
          </button>
          <button 
            className={styles.readButton} 
            disabled={!isConnected} 
            onClick={signTypedData}
          >
            Sign Typed Data (EIP-712)
          </button>
        </div>

        {contractState && (
          <div className={styles.stateCard}>
            <p>
              <strong>Balance:</strong> {formatEther(contractState)}
            </p>
          </div>
        )}

        {signatureResult && (
          <div className={styles.stateCard}>
            <p>
              <strong>Signature:</strong>
            </p>
            <p style={{ wordBreak: 'break-all', fontSize: '0.8em' }}>
              {signatureResult}
            </p>
          </div>
        )}

        {error && <p>Error reading balance: {error.message}</p>}
      </main>
    </div>
  )
}

export default Home
