// AUTO-GENERATED by scripts/generate-addresses.ts — do not edit by hand.
// Source of truth: ignition/deployments/chain-*/deployed_addresses.json + address-overrides.json.
// Regenerate with: pnpm gen:addresses (CI fails on drift).

/** Canonical ERC-4337 EntryPoint v0.7. */
export const ENTRYPOINT_V07_ADDRESS = '0x0000000071727De22E5E9d8BAf0edAc6f37da032' as const;

export type GianoDeployment = {
  /** ERC-4337 EntryPoint the wallets are bound to. */
  entryPoint: `0x${string}`;
  /** GianoSmartWalletFactory. */
  factory: `0x${string}`;
  /** GianoSmartWallet implementation behind the factory's proxies. */
  implementation: `0x${string}`;
  /**
   * Production sponsorship paymaster (the UUPS proxy). This is the address tenants send funding
   * to, so it must stay stable: changing it means every tenant re-learns where to fund, and any
   * payment already in flight to the old address is lost.
   */
  sponsorshipPaymaster?: `0x${string}`;
  /** Implementation behind {@link sponsorshipPaymaster}. Changes on every upgrade. */
  sponsorshipPaymasterImplementation?: `0x${string}`;
  /**
   * Testing-only permissive paymaster. Deliberately a different field from
   * {@link sponsorshipPaymaster} so that no consumer can pass one where the other is meant —
   * the separation is structural rather than a matter of operator discipline.
   */
  testPaymaster?: `0x${string}`;
  /** Testing-only ERC-20 (not deployed on production chains). */
  testErc20?: `0x${string}`;
};

export const gianoAddresses: Record<number, GianoDeployment> = {
  8453: {
    entryPoint: '0x0000000071727De22E5E9d8BAf0edAc6f37da032',
    factory: '0x26dCd29390eba3B22BcCbd2143989E5994Ac7050',
    implementation: '0x15cC758f7D3188c2361f6141CEaa9Ab2792bea56',
  },
  84532: {
    entryPoint: '0x0000000071727De22E5E9d8BAf0edAc6f37da032',
    factory: '0x26dCd29390eba3B22BcCbd2143989E5994Ac7050',
    implementation: '0x15cC758f7D3188c2361f6141CEaa9Ab2792bea56',
  },
};

/** Returns the Giano deployment for a chain, throwing a descriptive error for unknown chains. */
export function getGianoDeployment(chainId: number): GianoDeployment {
  const deployment = gianoAddresses[chainId];
  if (!deployment) {
    const known = Object.keys(gianoAddresses).join(', ');
    throw new Error(`No Giano deployment registered for chain ${chainId}. Known chains: ${known}`);
  }
  return deployment;
}
